### ISSUE TITLE
request $fetch 的 headers 怎么设置

### ISSUE THREAD

**Issue by GuanLola** [nicejade/quickapp-boilerplate-template#4]
.fetch({
        url: params.url,
        method: params.method,
        data: params.data,
        headers: {
          'token': ''
        }
      })
好像这样不生效

**Comment by nicejade** [comment]
@GuanLola  具体参见这个 [fetch header](https://doc.quickapp.cn/features/system/fetch.html?h=header) 接口；从文档上看，这个 字段用的是 `header`，没有这个 `s`；可以修改下试试看。
